-- ============================================================
-- ADETIC — Setup complet table contacts + Realtime
-- À exécuter dans Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. Créer la table contacts
CREATE TABLE IF NOT EXISTS contacts (
  id bigint generated by default as identity primary key,
  nom text,
  email text,
  message text,
  statut text default 'Nouveau',
  created_at timestamp with time zone default timezone('utc', now())
);

ALTER TABLE contacts ADD COLUMN IF NOT EXISTS statut text DEFAULT 'Nouveau';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT timezone('utc', now());

-- 2. Activer RLS
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- 3. Politiques RLS
DROP POLICY IF EXISTS "public insert contacts" ON contacts;
CREATE POLICY "public insert contacts" ON contacts
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "admin_select_contacts" ON contacts;
CREATE POLICY "admin_select_contacts" ON contacts
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "admin_update_contacts" ON contacts;
CREATE POLICY "admin_update_contacts" ON contacts
  FOR UPDATE USING (true) WITH CHECK (true);

-- 4. Activer Realtime sur toutes les tables du projet
ALTER PUBLICATION supabase_realtime ADD TABLE contacts;
ALTER PUBLICATION supabase_realtime ADD TABLE demandes_domaine;
ALTER PUBLICATION supabase_realtime ADD TABLE demandes_equipement;
ALTER PUBLICATION supabase_realtime ADD TABLE declarations_panne;
ALTER PUBLICATION supabase_realtime ADD TABLE demandes_email;
ALTER PUBLICATION supabase_realtime ADD TABLE demandes_plateforme;
