-- ============================================================
-- ADETIC — Correction de la table contacts
-- À exécuter dans Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. Créer la table contacts si elle n'existe pas
CREATE TABLE IF NOT EXISTS contacts (
  id bigint generated by default as identity primary key,
  nom text,
  email text,
  message text,
  statut text default 'Nouveau',
  created_at timestamp with time zone default timezone('utc', now())
);

-- 2. Ajouter les colonnes manquantes si la table existe déjà
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS statut text DEFAULT 'Nouveau';
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT timezone('utc', now());

-- 3. Activer RLS
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- 4. Politique INSERT (pour que le formulaire public puisse envoyer)
DROP POLICY IF EXISTS "public insert contacts" ON contacts;
CREATE POLICY "public insert contacts" ON contacts
  FOR INSERT WITH CHECK (true);

-- 5. Politique SELECT (pour que l'admin puisse lire)
DROP POLICY IF EXISTS "admin_select_contacts" ON contacts;
CREATE POLICY "admin_select_contacts" ON contacts
  FOR SELECT USING (true);

-- 6. Politique UPDATE (pour changer le statut depuis le dashboard)
DROP POLICY IF EXISTS "admin_update_contacts" ON contacts;
CREATE POLICY "admin_update_contacts" ON contacts
  FOR UPDATE USING (true) WITH CHECK (true);
