-- Supabase SQL schema for ADETIC website
-- Run this in the SQL editor of your Supabase project.

-- Table for site news / actualités
create table if not exists actualites (
  id bigint generated by default as identity primary key,
  category text not null,
  date text not null,
  title text not null,
  excerpt text not null,
  content text,
  color text not null,
  icon text,
  image_url text,
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists actualites enable row level security;
drop policy if exists "public select actualites" on actualites;
create policy "public select actualites" on actualites
  for select using (true);

-- Table for contact form submissions
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  nom text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Optional table for activities / missions
create table if not exists activites (
  id bigint generated by default as identity primary key,
  icon text,
  title text not null,
  description text not null,
  color text not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- E-Services: demandes de nom de domaine .td
create table if not exists demandes_domaine (
  id bigint generated by default as identity primary key,
  domaine_souhaite text not null,
  type_entite text not null,
  nom_organisation text not null,
  nom_contact text not null,
  email text not null,
  telephone text not null,
  adresse text,
  usage_description text,
  statut text default 'En attente',
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists demandes_domaine enable row level security;
drop policy if exists "public insert demandes_domaine" on demandes_domaine;
create policy "public insert demandes_domaine" on demandes_domaine
  for insert with check (true);

-- E-Services: demandes d'installation d'équipements
create table if not exists demandes_equipement (
  id bigint generated by default as identity primary key,
  type_equipement text not null,
  quantite integer,
  nom_organisation text not null,
  localisation_ville text not null,
  adresse_exacte text,
  responsable_nom text not null,
  responsable_email text not null,
  responsable_telephone text,
  date_souhaitee text,
  description_besoins text,
  statut text default 'En attente',
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists demandes_equipement enable row level security;
drop policy if exists "public insert demandes_equipement" on demandes_equipement;
create policy "public insert demandes_equipement" on demandes_equipement
  for insert with check (true);

-- E-Services: déclarations de panne technique
create table if not exists declarations_panne (
  id bigint generated by default as identity primary key,
  type_panne text not null,
  niveau_urgence text not null,
  localisation text not null,
  equipement_concerne text,
  nombre_utilisateurs_affectes integer,
  description_panne text not null,
  nom_declarant text not null,
  email_declarant text not null,
  telephone_declarant text,
  statut text default 'Ouvert',
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists declarations_panne enable row level security;
drop policy if exists "public insert declarations_panne" on declarations_panne;
create policy "public insert declarations_panne" on declarations_panne
  for insert with check (true);
