-- Supabase SQL schema for ADETIC website
-- Run this in the SQL editor of your Supabase project.

-- Table for site news / actualités
create table if not exists actualites (
  id bigint generated by default as identity primary key,
  category text not null,
  date text not null,
  title text not null,
  excerpt text not null,
  color text not null,
  icon text,
  image_url text,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Table for contact form submissions
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  nom text not null,
  email text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc', now())
);

-- Optional table for activities / missions
create table if not exists activites (
  id bigint generated by default as identity primary key,
  icon text,
  title text not null,
  description text not null,
  color text not null,
  created_at timestamp with time zone default timezone('utc', now())
);
