-- ============================================================
-- ADETIC — Tables pour les 2 nouveaux E-Services
-- À exécuter dans Supabase Dashboard → SQL Editor
-- ============================================================

-- 1. Création de boîtes mail professionnelles
CREATE TABLE IF NOT EXISTS demandes_email (
  id bigint generated by default as identity primary key,
  nom_organisation text not null,
  domaine_email text not null,
  nombre_comptes integer not null,
  liste_utilisateurs text,
  type_usage text,
  nom_responsable text not null,
  email_responsable text not null,
  telephone_responsable text,
  statut text default 'En attente',
  created_at timestamp with time zone default timezone('utc', now())
);

ALTER TABLE demandes_email ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public insert demandes_email" ON demandes_email;
CREATE POLICY "public insert demandes_email" ON demandes_email
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "admin_select_demandes_email" ON demandes_email;
CREATE POLICY "admin_select_demandes_email" ON demandes_email
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "admin_update_demandes_email" ON demandes_email;
CREATE POLICY "admin_update_demandes_email" ON demandes_email
  FOR UPDATE USING (true) WITH CHECK (true);

-- 2. Conception de plateformes numériques
CREATE TABLE IF NOT EXISTS demandes_plateforme (
  id bigint generated by default as identity primary key,
  nom_projet text not null,
  type_plateforme text not null,
  nom_organisation text not null,
  description_besoins text not null,
  fonctionnalites text,
  budget_approximatif text,
  delai_souhaite text,
  nom_responsable text not null,
  email_responsable text not null,
  telephone_responsable text,
  statut text default 'En attente',
  created_at timestamp with time zone default timezone('utc', now())
);

ALTER TABLE demandes_plateforme ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "public insert demandes_plateforme" ON demandes_plateforme;
CREATE POLICY "public insert demandes_plateforme" ON demandes_plateforme
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "admin_select_demandes_plateforme" ON demandes_plateforme;
CREATE POLICY "admin_select_demandes_plateforme" ON demandes_plateforme
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "admin_update_demandes_plateforme" ON demandes_plateforme;
CREATE POLICY "admin_update_demandes_plateforme" ON demandes_plateforme
  FOR UPDATE USING (true) WITH CHECK (true);
