-- ============================================================
-- ADETIC — Données initiales à exécuter dans l'éditeur SQL Supabase
-- ============================================================

-- 1. Ajouter la colonne content si elle n'existe pas encore
alter table actualites add column if not exists content text;

-- 2. Peupler la table actualites
INSERT INTO actualites (category, date, title, excerpt, content, color, icon, image_url) VALUES
(
  'Forum',
  '16–21 Fév 2026',
  'Participation stratégique du Tchad au Forum sur la Gouvernance de l''Internet de l''Afrique Centrale',
  'Du 16 au 21 février 2026, le Tchad a pris une part active au Forum sur la Gouvernance de l''Internet, renforçant sa position comme acteur clé du numérique africain.',
  'Le Tchad a défendu une vision de gouvernance inclusive, soulignant l''importance d''une infrastructure numérique souveraine et d''un accès universel au premier plan des politiques nationales.',
  '#00C9A7',
  '🌐',
  'igf-reunion.jpg'
),
(
  'Coopération',
  'Fév 2026',
  'Coopération numérique : des experts azerbaïdjanais en visite de travail à l''ADETIC',
  'Dans le cadre du renforcement de la coopération internationale en matière de transformation digitale, une délégation d''experts azerbaïdjanais a effectué une visite officielle.',
  'Les échanges ont porté sur des projets de connectivité, des solutions d''interopérabilité et l''accompagnement des startups tchadiennes vers des partenariats technologiques durables.',
  '#4F8EF7',
  '🤝',
  'rencontre-dg-et-smart.jpg'
),
(
  'Data Center',
  'Fév 2026',
  'Audit et certification du Data Center national : l''ADETIC, l''ANSICE et TECHSO-GROUP en mission conjointe',
  'Dans le cadre de la mise en œuvre de l''accord tripartite, l''ADETIC s''engage pour la certification du datacenter national tchadien.',
  'L''audit porte sur l''architecture, la résilience et la conformité aux meilleures pratiques internationales, assurant ainsi la sécurité des données publiques de l''État.',
  '#F7B731',
  '🖥️',
  'fond-humain-de-poignee-de-main-de-robot-ere-numerique-futuriste-2048x1365.jpg'
),
(
  'Intelligence Artificielle',
  '2025',
  'Formation de haut niveau sur l''Intelligence Artificielle',
  'L''ADETIC, en collaboration avec l''UNESCO et l''ENASTIC, organise une formation d''excellence sur l''IA pour les cadres nationaux.',
  'La formation vise à renforcer les compétences en data science, apprentissage automatique et gouvernance éthique de l''IA au sein des administrations publiques tchadiennes.',
  '#FC5C65',
  '🤖',
  'pexels-photo-1054397-1.jpeg'
);

-- 2. Créer les nouvelles tables E-Services si elles n'existent pas encore
-- (copier-coller depuis supabase_schema.sql si nécessaire)

create table if not exists demandes_domaine (
  id bigint generated by default as identity primary key,
  domaine_souhaite text not null,
  type_entite text not null,
  nom_organisation text not null,
  nom_contact text not null,
  email text not null,
  telephone text not null,
  adresse text,
  usage_description text,
  statut text default 'En attente',
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists demandes_domaine enable row level security;

drop policy if exists "public insert demandes_domaine" on demandes_domaine;
create policy "public insert demandes_domaine" on demandes_domaine
  for insert with check (true);

create table if not exists demandes_equipement (
  id bigint generated by default as identity primary key,
  type_equipement text not null,
  quantite integer,
  nom_organisation text not null,
  localisation_ville text not null,
  adresse_exacte text,
  responsable_nom text not null,
  responsable_email text not null,
  responsable_telephone text,
  date_souhaitee text,
  description_besoins text,
  statut text default 'En attente',
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists demandes_equipement enable row level security;

drop policy if exists "public insert demandes_equipement" on demandes_equipement;
create policy "public insert demandes_equipement" on demandes_equipement
  for insert with check (true);

create table if not exists declarations_panne (
  id bigint generated by default as identity primary key,
  type_panne text not null,
  niveau_urgence text not null,
  localisation text not null,
  equipement_concerne text,
  nombre_utilisateurs_affectes integer,
  description_panne text not null,
  nom_declarant text not null,
  email_declarant text not null,
  telephone_declarant text,
  statut text default 'Ouvert',
  created_at timestamp with time zone default timezone('utc', now())
);

alter table if exists declarations_panne enable row level security;

drop policy if exists "public insert declarations_panne" on declarations_panne;
create policy "public insert declarations_panne" on declarations_panne
  for insert with check (true);
